# Generated by Django 3.2.12 on 2024-01-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_1',
            new_name='strIngredient1',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_10',
            new_name='strIngredient10',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_11',
            new_name='strIngredient11',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_12',
            new_name='strIngredient12',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_13',
            new_name='strIngredient13',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_14',
            new_name='strIngredient14',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_15',
            new_name='strIngredient15',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_2',
            new_name='strIngredient2',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_3',
            new_name='strIngredient3',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_4',
            new_name='strIngredient4',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_5',
            new_name='strIngredient5',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_6',
            new_name='strIngredient6',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_7',
            new_name='strIngredient7',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_8',
            new_name='strIngredient8',
        ),
        migrations.RenameField(
            model_name='shoppingguide',
            old_name='ingredient_9',
            new_name='strIngredient9',
        ),
    ]
