# Generated by Django 3.2.12 on 2024-01-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20240123_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_10',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_11',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_12',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_13',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_14',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_15',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_7',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_8',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingguide',
            name='ingredient_9',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
